import type { CliInput } from "../pipedown.d.ts";
import { pd, std } from "../deps.ts";
import { getProjectBuildDir, getProjectName } from "./helpers.ts";
import { cliHelpTemplate } from "../stringTemplates.ts";

const helpText = cliHelpTemplate({
  title: "Clean",
  command: "pd clean",
  sections: [
    "Removes everything generated by Pipedown for the current project.",
    `Options:
    -j, --json    Output the build information as JSON.
    -p, --pretty  Pretty print the JSON output.
    -d, --debug   Display debug information.
    -h, --help    Display this message.`,
  ],
});

export async function cleanCommand(input: CliInput) {
  if (pd.$p.get(input, "/flags/help") || pd.$p.get(input, "/flags/h")) {
    console.log(helpText);
  } else {
    const projectName = getProjectName(input.globalConfig);
    const buildDir = getProjectBuildDir(projectName);
    console.log(std.colors.brightGreen(`Cleaning up ${buildDir}...`));
    try {
      await Deno.remove(buildDir, { recursive: true });
      console.log(std.colors.brightGreen("Done!"));
    } catch (e) {
      if (!(e instanceof Deno.errors.NotFound)) throw e;
      console.log(std.colors.brightYellow("Build directory not found, nothing to clean."));
    }
  }
  return input;
}
