import type {pdCliInput} from "./mod.ts";

export function helpCommand(input: pdCliInput) {
  console.log(`Pipedown.
Markdown to Pipe! Literate Markdown for any usecase.

    Usage: pd [options] [command]

    Commands:
        help    You're reading it!
        build   Generate scripts for all markdown files in current directory
        run     Run a script generated by pd
        test    Run tests for all scripts generated by pd
        list    List all scripts generated by pd
        clean   Remove all scripts generated by pd
            
`);
  return input;
}
