import { pd } from "../deps.ts";
import { pdBuild } from "../pdBuild.ts";
import { cliHelpTemplate } from "../stringTemplates.ts";
import { PD_DIR } from "./helpers.ts";
import type { CliInput } from "../pipedown.d.ts";

const helpText = cliHelpTemplate({
  title: "Test",
  command: "pd test",
  sections: [
    "Run tests for all scripts generated by pd",
    `Options:
    --record      Record cassettes for mock-flagged steps (VCR mode).
    --replay      Replay from cassettes, skip mock step execution.
    -j, --json    Output the build information as JSON.
    -p, --pretty  Pretty print the JSON output.
    -d, --debug   Display debug information.
    -h, --help    Display this message.`,
  ],
});

const args = [
  "test",
  "-A",
  "--unstable-kv",
  `--config=${PD_DIR}/deno.json`,
  "--no-check",
];

export async function testCommand(input: CliInput) {
  if (pd.$p.get(input, "/flags/help") || pd.$p.get(input, "/flags/h")) {
    console.log(helpText);
  } else {
    await pdBuild(input);

    // VCR mode: pass through to test template via env var
    const env: Record<string, string> = {};
    if (pd.$p.get(input, "/flags/record")) {
      env.PD_VCR_MODE = "record";
    } else if (pd.$p.get(input, "/flags/replay")) {
      env.PD_VCR_MODE = "replay";
    }

    if (input.flags["--"].length > 0) {
      args.push("--");
      args.push(...input.flags["--"]);
    }
    const test = new Deno.Command(Deno.execPath(), {
      args,
      stdout: "piped",
      stderr: "piped",
      env,
    });

    const decoder = new TextDecoder();
    const output = await test.output();
    const error = decoder.decode(output.stderr);
    const out = decoder.decode(output.stdout);
    console.log(out);
    if (error) {
      console.error(error);
    }
  }

  return input;
}

export function updateTestCommand(input: CliInput) {
  input.flags["--"].push("--update");
  return testCommand(input);
}
